version: '2'
services:
  data-volume:
    container_name: 'data-volume'
    image: busybox
    volumes: 
      - ./data/www:/var/www
      # - ../../src:/var/www/html
      - ./data/mysql:/var/lib/mysql
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ./logs/nginx:/var/log/nginx
      - ./logs/php-fpm:/var/log/php-fpm
      - ./logs/mysql:/var/log/mysql
  web:
    container_name: nginx1.13.5-alpine
    image: nginx:1.13.5-alpine
    ports:
      - 80:80
    volumes_from:
      - data-volume
    working_dir: /var/www

  app:
    container_name: php7-fpm
    # for install mysql mysqli, pdo driver
    build: ./conf/php-fpm
    ports:
      - 9000:9000
    volumes_from:
      - data-volume
    working_dir: /var/www

  db:
    container_name: mysql5.7
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes_from:
      - data-volume
    working_dir: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
