version: '3'
services:

  web:
    container_name: docker-nginx
    env_file: .env
    build: ./conf/nginx
    working_dir: /var/www/html/htdocs
    tty: true
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      # @common
      #- /etc/localtime:/etc/localtime:ro
      # @nginx
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
      - "${SRC_DIR}:/var/www/html"
      #- ./conf/bash:/bin/bash
    networks:
      - lempnetwork

  app:
    container_name: docker-php7fpm
    build: ./conf/php-fpm
    working_dir: /var/www
    ports:
      - 9000:9000
    depends_on:
      - cache
      - db
    volumes:
      # @php-fpm
      - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./conf/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./log/php-fpm/logs:/var/log/php-fpm
      - ./log/php-fpm/logs:/var/www/html/logs
      - "${SRC_DIR}:/var/www/html"
    networks:
      - lempnetwork

  cache:
    container_name: docker-memcached
    image: memcached:1.5.16-alpine
    ports:
      - 11211:11211
    volumes:
      # @memcached
      - ./conf/memcached/memcached:/etc/sysconfig/memcached
    networks:
      - lempnetwork

  db:
    container_name: docker-mysql57
    image: mysql:5.7.27
    working_dir: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      # @mysql
      - ./conf/mysql:/etc/mysql
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql/:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - lempnetwork

  system-monitor:
    container_name: docker-monitor
    image: titpetric/netdata:1.14.0
    volumes:
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "19999:19999"
    restart: always
    networks:
      - lempnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    container_name: docker-phpMyAdmin
    ports:
        - "8888:80"
    environment:        
      PMA_ARBITRARY: 1
    networks:
      - lempnetwork
#Docker Networks
networks:
  lempnetwork:
    driver: bridge