version: '2'
services:

  data-volume:
    container_name: docker-data
    image: busybox
    # env_file: .env
    volumes:
      # @nginx
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
      - "${SRC_DIR}:/var/www/html"
      # @php-fpm
      - ./conf/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ./log/php-fpm:/var/log/php-fpm
      # @mysql
      - ./conf/mysql:/etc/mysql
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql

  web:
    container_name: docker-nginx
    build: ./conf/nginx
    working_dir: /var/www
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - data-volume

  app:
    container_name: docker-php7fpm
    build: ./conf/php-fpm
    working_dir: /var/www
    ports:
      - 9000:9000
    links:
      - cache
      - db
    volumes_from:
      - data-volume

  cache:
    container_name: docker-memcached
    build: ./conf/memcached
    ports:
      - 11211:11211
    volumes_from:
      - data-volume

  db:
    container_name: docker-mysql57
    build: ./conf/mysql
    working_dir: /var/lib/mysql
    ports:
      - 3306:3306
    volumes_from:
      - data-volume
    environment:
      MYSQL_ROOT_PASSWORD: password
