version: '2'
services:
  data-volume:
    container_name: 'data-volume'
    image: busybox
    volumes: 
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ./conf/mysql:/etc/mysql
      # - ./data/www:/var/www
      - ../../src:/var/www/html
      - ./data/mysql:/var/lib/mysql
      - ./log/nginx:/var/log/nginx
      - ./log/php-fpm:/var/log/php-fpm
      - ./log/mysql:/var/log/mysql
  web:
    container_name: nginx1.13.5-alpine
    build: ./conf/nginx
    working_dir: /var/www
    ports:
      - 80:80
    volumes_from:
      - data-volume

  app:
    container_name: php7-fpm
    build: ./conf/php-fpm
    working_dir: /var/www
    ports:
      - 9000:9000
    volumes_from:
      - data-volume

  db:
    container_name: mysql5.7
    build: ./conf/mysql
    working_dir: /var/lib/mysql
    ports:
      - 3306:3306
    volumes_from:
      - data-volume
    environment:
      MYSQL_ROOT_PASSWORD: root
