version: '2'
services:
  data-volume:
    container_name: 'data-volume'
    image: busybox
    volumes: 
      - ./data/www:/var/www
      - ./data/mysql:/var/lib/mysql
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/php-fpm/www.conf:/etc/php-fpm.d/www.conf
      - ./logs/nginx:/var/log/nginx
      - ./logs/php-fpm:/var/log/php-fpm
      - ./logs/mysql/mysqld.log:/var/log/mysqld.log
  web:
    container_name: nginx1.13.5-alpine
    image: nginx:1.13.5-alpine
    ports:
      - 80:80
    volumes_from:
      - data-volume
  app:
    container_name: php7-fpm
    image: php:7-fpm-alpine
    ports:
      - 9000:9000
    volumes_from:
      - data-volume
  db:
    container_name: mysql5.7
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes_from:
      - data-volume
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
